from __future__ import annotations

import csv
from pathlib import Path


LAB = Path(__file__).resolve().parents[1]


def write_rows(path: Path, fieldnames: list[str], rows: list[dict[str, object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def regulation_rows() -> list[dict[str, object]]:
    return [
        {
            "country_id": "coordinated_welfare_a",
            "region": "europe",
            "income_group": "high_income",
            "regime_type": "coordinated_welfare_state",
            "legal_origin": "civil_law",
            "employment_law_index": 0.78,
            "collective_relations_index": 0.86,
            "social_security_index": 0.82,
            "legal_coverage_rate": 0.84,
            "union_membership_rate": 0.31,
            "bargaining_coverage_rate": 0.76,
            "enforcement_capacity_index": 0.87,
            "informality_rate": 0.08,
            "unemployment_rate": 0.061,
            "formal_employment_share": 0.88,
        },
        {
            "country_id": "liberal_market_b",
            "region": "anglo",
            "income_group": "high_income",
            "regime_type": "liberal_market",
            "legal_origin": "common_law",
            "employment_law_index": 0.42,
            "collective_relations_index": 0.36,
            "social_security_index": 0.48,
            "legal_coverage_rate": 0.66,
            "union_membership_rate": 0.12,
            "bargaining_coverage_rate": 0.18,
            "enforcement_capacity_index": 0.78,
            "informality_rate": 0.10,
            "unemployment_rate": 0.047,
            "formal_employment_share": 0.86,
        },
        {
            "country_id": "dual_welfare_c",
            "region": "southern_europe",
            "income_group": "high_income",
            "regime_type": "dual_welfare_state",
            "legal_origin": "civil_law",
            "employment_law_index": 0.75,
            "collective_relations_index": 0.62,
            "social_security_index": 0.71,
            "legal_coverage_rate": 0.72,
            "union_membership_rate": 0.18,
            "bargaining_coverage_rate": 0.63,
            "enforcement_capacity_index": 0.63,
            "informality_rate": 0.18,
            "unemployment_rate": 0.112,
            "formal_employment_share": 0.75,
        },
        {
            "country_id": "industrializing_d",
            "region": "latin_america",
            "income_group": "upper_middle_income",
            "regime_type": "formalizing_development",
            "legal_origin": "civil_law",
            "employment_law_index": 0.69,
            "collective_relations_index": 0.57,
            "social_security_index": 0.64,
            "legal_coverage_rate": 0.58,
            "union_membership_rate": 0.14,
            "bargaining_coverage_rate": 0.28,
            "enforcement_capacity_index": 0.49,
            "informality_rate": 0.39,
            "unemployment_rate": 0.084,
            "formal_employment_share": 0.55,
        },
        {
            "country_id": "informal_development_e",
            "region": "south_asia",
            "income_group": "lower_middle_income",
            "regime_type": "high_informality",
            "legal_origin": "common_law",
            "employment_law_index": 0.62,
            "collective_relations_index": 0.51,
            "social_security_index": 0.44,
            "legal_coverage_rate": 0.41,
            "union_membership_rate": 0.07,
            "bargaining_coverage_rate": 0.10,
            "enforcement_capacity_index": 0.32,
            "informality_rate": 0.71,
            "unemployment_rate": 0.058,
            "formal_employment_share": 0.26,
        },
        {
            "country_id": "resource_informal_f",
            "region": "sub_saharan_africa",
            "income_group": "lower_middle_income",
            "regime_type": "high_informality",
            "legal_origin": "mixed",
            "employment_law_index": 0.58,
            "collective_relations_index": 0.46,
            "social_security_index": 0.38,
            "legal_coverage_rate": 0.36,
            "union_membership_rate": 0.09,
            "bargaining_coverage_rate": 0.14,
            "enforcement_capacity_index": 0.28,
            "informality_rate": 0.76,
            "unemployment_rate": 0.073,
            "formal_employment_share": 0.22,
        },
        {
            "country_id": "migration_gateway_g",
            "region": "europe_border",
            "income_group": "high_income",
            "regime_type": "migration_gateway",
            "legal_origin": "civil_law",
            "employment_law_index": 0.61,
            "collective_relations_index": 0.58,
            "social_security_index": 0.67,
            "legal_coverage_rate": 0.69,
            "union_membership_rate": 0.22,
            "bargaining_coverage_rate": 0.48,
            "enforcement_capacity_index": 0.75,
            "informality_rate": 0.13,
            "unemployment_rate": 0.052,
            "formal_employment_share": 0.82,
        },
        {
            "country_id": "supply_chain_node_h",
            "region": "east_asia",
            "income_group": "upper_middle_income",
            "regime_type": "export_supply_chain",
            "legal_origin": "civil_law",
            "employment_law_index": 0.55,
            "collective_relations_index": 0.41,
            "social_security_index": 0.53,
            "legal_coverage_rate": 0.52,
            "union_membership_rate": 0.10,
            "bargaining_coverage_rate": 0.19,
            "enforcement_capacity_index": 0.58,
            "informality_rate": 0.31,
            "unemployment_rate": 0.039,
            "formal_employment_share": 0.62,
        },
    ]


def comparative_case_rows() -> list[dict[str, object]]:
    return [
        {
            "case_id": "labor_regulation_cross_country",
            "anchor": "Botero et al. 2004",
            "comparative_unit": "country",
            "institutional_domain": "labor_regulation_index",
            "identifying_variation": "cross-country variation in coded employment, collective, and social-security law",
            "observed_margin": "rules-on-paper regulation and institutional correlates",
            "implementation_gap": "high",
            "portability_risk": "medium",
            "mechanism_travels": "legal coding clarifies formal institutional differences",
            "estimate_travels": "no single effect size transports without enforcement data",
        },
        {
            "case_id": "swiss_cross_border_opening",
            "anchor": "Beerli et al. 2021",
            "comparative_unit": "border region and firm",
            "institutional_domain": "migration_regime",
            "identifying_variation": "differential exposure to abolition of cross-border worker restrictions",
            "observed_margin": "firm performance, employment, and worker outcomes",
            "implementation_gap": "low",
            "portability_risk": "medium",
            "mechanism_travels": "migration regimes alter matching and firm labor supply",
            "estimate_travels": "depends on skill mix, commuting geography, and bargaining institutions",
        },
        {
            "case_id": "nike_supplier_management",
            "anchor": "Distelhorst-Hainmueller-Locke 2017",
            "comparative_unit": "supplier factory",
            "institutional_domain": "private_supply_chain_governance",
            "identifying_variation": "variation in management practices and supplier exposure",
            "observed_margin": "labor standards compliance and social performance",
            "implementation_gap": "medium",
            "portability_risk": "high",
            "mechanism_travels": "buyers and management systems can alter supplier incentives",
            "estimate_travels": "depends on buyer commitment, audit credibility, and worker voice",
        },
        {
            "case_id": "informality_development_comparison",
            "anchor": "Ulyssea 2020",
            "comparative_unit": "firm and worker sector",
            "institutional_domain": "informality_regime",
            "identifying_variation": "variation in registration, inspection, and payroll enforcement across settings",
            "observed_margin": "formality, earnings, productivity, and compliance",
            "implementation_gap": "high",
            "portability_risk": "high",
            "mechanism_travels": "partial state reach changes formal-informal allocation",
            "estimate_travels": "depends on taxes, benefits, firm size, and enforcement capacity",
        },
        {
            "case_id": "europe_immigrant_native_gaps",
            "anchor": "Guzi-Kahanec-Mydlikova 2021",
            "comparative_unit": "country and migrant group",
            "institutional_domain": "integration_regime",
            "identifying_variation": "cross-country institutional differences in immigrant labor-market access",
            "observed_margin": "immigrant-native labor-market gaps",
            "implementation_gap": "medium",
            "portability_risk": "medium",
            "mechanism_travels": "institutions condition integration and access",
            "estimate_travels": "depends on migrant composition and recognition rules",
        },
    ]


def transfer_rows() -> list[dict[str, object]]:
    return [
        {
            "design_id": "cross_country_legal_index",
            "anchor": "Botero et al. 2004",
            "setting": "labor-law coding across countries",
            "comparison_class": "national legal regimes",
            "design_family": "cross_country_index",
            "identifying_variation": "coded legal differences across countries",
            "observed_margin": "rules-on-paper regulation and coverage proxies",
            "portability_claim": "measurement framework travels better than effect size",
            "main_caution": "implementation and informality are not fully measured",
        },
        {
            "design_id": "migration_border_exposure",
            "anchor": "Beerli et al. 2021",
            "setting": "border regions exposed to cross-border labor access",
            "comparison_class": "regions and firms with different exposure",
            "design_family": "border_region_exposure",
            "identifying_variation": "differential exposure to migration-rule change",
            "observed_margin": "employment, firm performance, worker outcomes",
            "portability_claim": "mechanism of labor-market integration can travel",
            "main_caution": "effect size depends on geography, skills, and bargaining",
        },
        {
            "design_id": "informality_enforcement_rollout",
            "anchor": "Ulyssea 2020",
            "setting": "local enforcement expansion in a high-informality economy",
            "comparison_class": "regions with different state capacity",
            "design_family": "within_country_comparative_reform",
            "identifying_variation": "rollout or intensity of inspection capacity",
            "observed_margin": "formality, wages, compliance, firm size",
            "portability_claim": "formal-informal allocation mechanism can travel",
            "main_caution": "local fiscal capacity and private benefits of formality differ",
        },
        {
            "design_id": "harmonized_admin_microdata",
            "anchor": "Blanchard-Wolfers 2000",
            "setting": "linked worker data across welfare-state regimes",
            "comparison_class": "administrative regimes",
            "design_family": "comparative_administrative_microdata",
            "identifying_variation": "policy and regime differences in harmonized records",
            "observed_margin": "earnings, unemployment duration, mobility, benefit receipt",
            "portability_claim": "comparative margins can be harmonized if definitions are transparent",
            "main_caution": "institutions are bundled and measurement may differ",
        },
        {
            "design_id": "buyer_audit_exposure",
            "anchor": "Distelhorst-Hainmueller-Locke 2017",
            "setting": "supplier factories in a global production network",
            "comparison_class": "factories, buyers, and audit regimes",
            "design_family": "supply_chain_governance_data",
            "identifying_variation": "audit timing, buyer pressure, or management-practice exposure",
            "observed_margin": "labor standards compliance and working conditions",
            "portability_claim": "private-governance incentive mechanism can travel",
            "main_caution": "audit quality and worker voice may differ across chains",
        },
        {
            "design_id": "historical_bargaining_regime",
            "anchor": "Freeman 2007",
            "setting": "historical institutional classification of bargaining systems",
            "comparison_class": "regime families and sectors",
            "design_family": "historical_comparative_classification",
            "identifying_variation": "inherited bargaining institutions and sectoral exposure",
            "observed_margin": "wage compression, coverage, employment adjustment",
            "portability_claim": "taxonomy clarifies comparison classes",
            "main_caution": "historical categories can hide current implementation differences",
        },
    ]


def main() -> None:
    write_rows(
        LAB / "original" / "reduced" / "labor_regulation_index_synthetic.csv",
        [
            "country_id",
            "region",
            "income_group",
            "regime_type",
            "legal_origin",
            "employment_law_index",
            "collective_relations_index",
            "social_security_index",
            "legal_coverage_rate",
            "union_membership_rate",
            "bargaining_coverage_rate",
            "enforcement_capacity_index",
            "informality_rate",
            "unemployment_rate",
            "formal_employment_share",
        ],
        regulation_rows(),
    )
    write_rows(
        LAB / "original" / "reduced" / "comparative_cases_synthetic.csv",
        [
            "case_id",
            "anchor",
            "comparative_unit",
            "institutional_domain",
            "identifying_variation",
            "observed_margin",
            "implementation_gap",
            "portability_risk",
            "mechanism_travels",
            "estimate_travels",
        ],
        comparative_case_rows(),
    )
    write_rows(
        LAB / "transfer" / "data" / "comparative_designs_synthetic.csv",
        [
            "design_id",
            "anchor",
            "setting",
            "comparison_class",
            "design_family",
            "identifying_variation",
            "observed_margin",
            "portability_claim",
            "main_caution",
        ],
        transfer_rows(),
    )
    print("Wrote Week 9 synthetic comparative data.")


if __name__ == "__main__":
    main()
